export type Country = { name: string; code: string };

export const countries: Country[] = [
  { name: "United States", code: "+1" },
  { name: "Canada", code: "+1" },
  { name: "United Kingdom", code: "+44" },
  { name: "Ireland", code: "+353" },
  { name: "Germany", code: "+49" },
  { name: "France", code: "+33" },
  { name: "Netherlands", code: "+31" },
  { name: "Belgium", code: "+32" },
  { name: "Spain", code: "+34" },
  { name: "Portugal", code: "+351" },
  { name: "Italy", code: "+39" },
  { name: "Switzerland", code: "+41" },
  { name: "Austria", code: "+43" },
  { name: "Sweden", code: "+46" },
  { name: "Norway", code: "+47" },
  { name: "Denmark", code: "+45" },
  { name: "Finland", code: "+358" },
  { name: "Poland", code: "+48" },
  { name: "Czechia", code: "+420" },
  { name: "Turkey", code: "+90" },
  { name: "United Arab Emirates", code: "+971" },
  { name: "Saudi Arabia", code: "+966" },
  { name: "Qatar", code: "+974" },
  { name: "Israel", code: "+972" },
  { name: "South Africa", code: "+27" },
  { name: "Nigeria", code: "+234" },
  { name: "Kenya", code: "+254" },
  { name: "Egypt", code: "+20" },
  { name: "India", code: "+91" },
  { name: "Pakistan", code: "+92" },
  { name: "Bangladesh", code: "+880" },
  { name: "Sri Lanka", code: "+94" },
  { name: "China", code: "+86" },
  { name: "Hong Kong", code: "+852" },
  { name: "Japan", code: "+81" },
  { name: "South Korea", code: "+82" },
  { name: "Singapore", code: "+65" },
  { name: "Malaysia", code: "+60" },
  { name: "Indonesia", code: "+62" },
  { name: "Thailand", code: "+66" },
  { name: "Vietnam", code: "+84" },
  { name: "Philippines", code: "+63" },
  { name: "Australia", code: "+61" },
  { name: "New Zealand", code: "+64" },
  { name: "Brazil", code: "+55" },
  { name: "Mexico", code: "+52" },
  { name: "Argentina", code: "+54" },
  { name: "Chile", code: "+56" },
  { name: "Colombia", code: "+57" },
];

export const priorities = [
  "Urgent — Need ASAP",
  "Medium — Normal Priority",
  "Low — Flexible Timeline",
];

export const connectionMethods = [
  "Email",
  "WhatsApp",
  "Microsoft Teams",
  "Zoom",
  "Google Meet",
  "Slack",
  "Telegram",
  "Phone Call",
  "LinkedIn",
];
